Repository Jigsaw-Code/outline-server, pull requests merged in 2022-10, with the labels that each got.

#1169 Revert "chore: updated translations for Outline manager"
  src/server_manager/messages/am.json
  src/server_manager/messages/ar.json
  src/server_manager/messages/az.json
  src/server_manager/messages/bg.json
  src/server_manager/messages/bs.json
  src/server_manager/messages/ca.json
  src/server_manager/messages/cs.json
  src/server_manager/messages/da.json
  src/server_manager/messages/de.json
  src/server_manager/messages/el.json
  src/server_manager/messages/en-GB.json
  src/server_manager/messages/es-419.json
  src/server_manager/messages/es.json
  src/server_manager/messages/et.json
  src/server_manager/messages/fa.json
  src/server_manager/messages/fi.json
  src/server_manager/messages/fil.json
  src/server_manager/messages/fr.json
  src/server_manager/messages/he.json
  src/server_manager/messages/hi.json
  src/server_manager/messages/hr.json
  src/server_manager/messages/hu.json
  src/server_manager/messages/hy.json
  src/server_manager/messages/id.json
  src/server_manager/messages/it.json
  src/server_manager/messages/ja.json
  src/server_manager/messages/ka.json
  src/server_manager/messages/kk.json
  src/server_manager/messages/km.json
  src/server_manager/messages/ko.json
  src/server_manager/messages/lt.json
  src/server_manager/messages/lv.json
  src/server_manager/messages/mk.json
  src/server_manager/messages/my.json
  src/server_manager/messages/nl.json
  src/server_manager/messages/no.json
  src/server_manager/messages/pl.json
  src/server_manager/messages/pt-BR.json
  src/server_manager/messages/pt-PT.json
  src/server_manager/messages/ro.json
  src/server_manager/messages/ru.json
  src/server_manager/messages/sk.json
  src/server_manager/messages/sl.json
  src/server_manager/messages/sq.json
  src/server_manager/messages/sr-Latn.json
  src/server_manager/messages/sr.json
  src/server_manager/messages/sv.json
  src/server_manager/messages/th.json
  src/server_manager/messages/tr.json
  src/server_manager/messages/uk.json
  src/server_manager/messages/ur.json
  src/server_manager/messages/vi.json
  src/server_manager/messages/zh-CN.json
  src/server_manager/messages/zh-TW.json
Labels: size/L

#1166 Revert "refactor(manager): replace share s3 flow with self-contained instructions"
  src/server_manager/messages/en.json
  src/server_manager/messages/master_messages.json
  src/server_manager/web_app/app.ts
  src/server_manager/web_app/ui_components/app-root.ts
  src/server_manager/web_app/ui_components/outline-share-dialog.ts
Labels: size/S

#1182 feat(devtools): add link to mattermost channel
  README.md
Labels: size/XS

#1168 build(manager/electron): 👷 add option to use GCP KMS for signing
  src/server_manager/electron_app/windows/sign_windows_executable.mjs
  third_party/jsign/METADATA
  third_party/jsign/jsign-4.0.jar
  third_party/jsign/jsign-4.2.jar
Labels: size/XS

#1181 chore: update package.json to set version as 1.12.0
  src/server_manager/package.json
Labels: size/XS

#1002 feat(server): add encryption method option to the access key creation API
  src/shadowbox/integration_test/test.sh
  src/shadowbox/model/access_key.ts
  src/shadowbox/model/errors.ts
  src/shadowbox/server/api.yml
  src/shadowbox/server/manager_service.spec.ts
  src/shadowbox/server/manager_service.ts
  src/shadowbox/server/server_access_key.spec.ts
  src/shadowbox/server/server_access_key.ts
Labels: cla: yes

#1214 chore(server): bump version for release
  src/shadowbox/docker/Dockerfile
  src/shadowbox/package.json
Labels: size/XS
