Repository Jigsaw-Code/outline-server, pull requests merged in 2022-11, with the labels that each got.

#1198 feat(manager/web): chunked invite flow - phase zero
  .github/workflows/pull_request_checks.yml
  src/server_manager/messages/am.json
  src/server_manager/messages/ar.json
  src/server_manager/messages/az.json
  src/server_manager/messages/bg.json
  src/server_manager/messages/bs.json
  src/server_manager/messages/ca.json
  src/server_manager/messages/cs.json
  src/server_manager/messages/da.json
  src/server_manager/messages/de.json
  src/server_manager/messages/el.json
  src/server_manager/messages/en-GB.json
  src/server_manager/messages/en.json
  src/server_manager/messages/es-419.json
  src/server_manager/messages/es.json
  src/server_manager/messages/et.json
  src/server_manager/messages/fa.json
  src/server_manager/messages/fi.json
  src/server_manager/messages/fil.json
  src/server_manager/messages/fr.json
  src/server_manager/messages/he.json
  src/server_manager/messages/hi.json
  src/server_manager/messages/hr.json
  src/server_manager/messages/hu.json
  src/server_manager/messages/hy.json
  src/server_manager/messages/id.json
  src/server_manager/messages/it.json
  src/server_manager/messages/ja.json
  src/server_manager/messages/ka.json
  src/server_manager/messages/kk.json
  src/server_manager/messages/km.json
  src/server_manager/messages/ko.json
  src/server_manager/messages/lt.json
  src/server_manager/messages/lv.json
  src/server_manager/messages/master_messages.json
  src/server_manager/messages/mk.json
  src/server_manager/messages/my.json
  src/server_manager/messages/nl.json
  src/server_manager/messages/no.json
  src/server_manager/messages/pl.json
  src/server_manager/messages/pt-BR.json
  src/server_manager/messages/pt-PT.json
  src/server_manager/messages/ro.json
  src/server_manager/messages/ru.json
  src/server_manager/messages/sk.json
  src/server_manager/messages/sl.json
  src/server_manager/messages/sq.json
  src/server_manager/messages/sr-Latn.json
  src/server_manager/messages/sr.json
  src/server_manager/messages/sv.json
  src/server_manager/messages/th.json
  src/server_manager/messages/tr.json
  src/server_manager/messages/uk.json
  src/server_manager/messages/ur.json
  src/server_manager/messages/vi.json
  src/server_manager/messages/zh-CN.json
  src/server_manager/messages/zh-TW.json
  src/server_manager/web_app/ui_components/outline-share-dialog.ts
Labels: manager, size/S

#1225 chore(manager): 🎉 release v1.13.0 for all platforms
  src/server_manager/package.json
Labels: release process, size/XS

#1237 fix(manager/web): 💊 show Sydney flag in DO region page
  src/server_manager/model/digitalocean.ts
Labels: size/XS

#1232 fix(server): don't output all log messages
  src/shadowbox/infrastructure/logging.ts
Labels: size/XS

#1238 fix(server): fix isPortUsed for IPv6
  src/shadowbox/infrastructure/get_port.spec.ts
  src/shadowbox/infrastructure/get_port.ts
Labels: size/XS
