Repository Jigsaw-Code/outline-server, pull requests merged in 2022-08, with the labels that each got.

#1132 fix: avoid malicious path traversal in manager's open-image method
  src/server_manager/electron_app/index.ts
Labels: size/XS

#1135 refactor(manager): ♻️ change electron-updater's url to S3
  src/server_manager/scripts/get_electron_build_flags.mjs
Labels: size/XS

#1133 refactor(manager): replace share s3 flow with self-contained instructions
  src/server_manager/messages/en.json
  src/server_manager/messages/master_messages.json
  src/server_manager/web_app/app.ts
  src/server_manager/web_app/ui_components/app-root.ts
  src/server_manager/web_app/ui_components/outline-share-dialog.ts
Labels: size/S

#1138 fix(manager): removes special case for manager connection key
  src/server_manager/images/manager-key-avatar.svg
  src/server_manager/messages/en.json
  src/server_manager/messages/master_messages.json
  src/server_manager/web_app/app.ts
  src/server_manager/web_app/ui_components/outline-server-view.ts
Labels: size/M

#1148 feat(manager): upgrade DigitalOcean image
  src/server_manager/README.md
  src/server_manager/cloud/digitalocean_api.ts
  src/server_manager/electron_app/build.action.sh
  src/server_manager/install_scripts/do_install_server.sh
  src/server_manager/web_app/digitalocean_account.ts
Labels: size/XS

#1151 chore(manager): clean up Manager errors
  src/server_manager/cloud/digitalocean_api.ts
  src/server_manager/infrastructure/custom_error.ts
  src/server_manager/infrastructure/errors.ts
  src/server_manager/infrastructure/path_api.ts
  src/server_manager/model/server.ts
  src/server_manager/web_app/app.ts
  src/server_manager/web_app/digitalocean_server.ts
  src/server_manager/web_app/gcp_account.ts
  src/server_manager/web_app/gcp_server.ts
  src/shadowbox/model/errors.ts
Labels: size/M

#1153 fix(devtools): only run the size label on internal PRs
  .github/workflows/pull_request_checks.yml
Labels: size/XS

#1157 fix: don't close the oauth callback server on bad requests
  src/server_manager/electron_app/digitalocean_oauth.ts
Labels: size/XS
