Repository Jigsaw-Code/outline-server, pull requests merged in 2022-06, with the labels that each got.

#1103 chore(devtools): non-build updates from client
  .browserslistrc
  .eslintrc.json
  .github/workflows/build_and_test_debug.yml
  .github/workflows/build_release_candidates.yml
  .github/workflows/manager_linux_build_release_candidate.yml
  .github/workflows/manager_linux_publish_release.yml
  .github/workflows/pull_request_checks.yml
  .travis.yml
  README.md
  commitlint.config.js
  package-lock.json
  package.json
  src/server_manager/README.md
  src/server_manager/scripts/get_electron_build_flags.mjs
Labels: size/L

#1104 build(manager): 👷 sign Windows apps during electron build
  src/server_manager/electron_app/windows/digicert-usb-config/eToken-macos.cfg
  src/server_manager/electron_app/windows/digicert-usb-config/eToken-windows.cfg
  src/server_manager/electron_app/windows/electron_builder_signing_plugin.cjs
  src/server_manager/electron_app/windows/sign_windows_executable.mjs
  src/server_manager/scripts/get_electron_build_flags.mjs
  third_party/jsign/LICENSE.txt
  third_party/jsign/METADATA
  third_party/jsign/jsign-4.0.jar
Labels: size/L

#1111 fix: broken link to invitation docs
  src/server_manager/web_app/ui_components/outline-share-dialog.ts
Labels: bug, size/XS

#1112 chore(manager): update version to 1.10.0
  src/server_manager/package.json
Labels: dependencies, size/XS

#1114 feat(devtools): partial import restrictions
  .eslintrc.json
  .github/workflows/build_and_test_debug.yml
  package-lock.json
  package.json
  src/server_manager/web_app/outline-gcp-create-server-app.ts
  src/server_manager/web_app/ui_components/app-root.ts
  src/shadowbox/infrastructure/text_file.ts
  src/shadowbox/server/mocks/mocks.ts
Labels: dependencies, release process, size/S

#1115 chore: delete macos-signing-certificate.p12.enc
  macos-signing-certificate.p12.enc
Labels: release process

#1116 chore(manager): show the GCP magic flow by default
  src/server_manager/base.webpack.js
  src/server_manager/web_app/ui_components/outline-intro-step.ts
Labels: size/XS

#1117 fix(manager): 💊 manager's icon is not shown in Ubuntu Dock
  src/server_manager/README.md
  src/server_manager/electron_app/index.ts
Labels: bug, size/XS
