Repository Jigsaw-Code/outline-server, pull requests merged in 2024-01, with the labels that each got.

#1467 fix(sentry_webhook): convert OS values to allowed picklist values
  src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts
  src/sentry_webhook/post_sentry_event_to_salesforce.ts
Labels: size/XS

#1469 chore(manager/web): clean up unused `_computeSideBarMarginClass`
  src/server_manager/web_app/ui_components/app-root.ts
Labels: size/XS

#1464 fix(server): make temp file names longer
  .github/workflows/build_and_test_debug.yml
  src/server_manager/install_scripts/install_server.sh
Labels: size/XS

#1473 feat(server): add optional `id` parameter to `createNewAccessKey` method
  src/shadowbox/model/access_key.ts
  src/shadowbox/model/errors.ts
  src/shadowbox/server/api.yml
  src/shadowbox/server/manager_service.spec.ts
  src/shadowbox/server/manager_service.ts
  src/shadowbox/server/server_access_key.spec.ts
  src/shadowbox/server/server_access_key.ts
Labels: size/XL

#1484 chore(server): remove docker-compose and cleanup
  package-lock.json
  package.json
  src/shadowbox/README.md
  src/shadowbox/docker/Dockerfile
  src/shadowbox/docker/build.action.sh
  src/shadowbox/docker/start.action.sh
  src/shadowbox/integration_test/README.md
  src/shadowbox/integration_test/client/Dockerfile
  src/shadowbox/integration_test/docker-compose.yml
  src/shadowbox/integration_test/run.action.sh
  src/shadowbox/integration_test/target/Dockerfile
  src/shadowbox/integration_test/test.sh
Labels: size/M

#1491 chore(server): inject version at build time
  src/shadowbox/docker/Dockerfile
  src/shadowbox/docker/build.action.sh
  src/shadowbox/package.json
  src/shadowbox/server/main.ts
  src/shadowbox/server/manager_service.ts
  src/shadowbox/server/shared_metrics.spec.ts
  src/shadowbox/server/shared_metrics.ts
  src/shadowbox/server/version.ts
  src/shadowbox/webpack.config.js
Labels: size/XS
