Repository Jigsaw-Code/outline-server, pull requests merged in 2024-04, with the labels that each got.

#1528 feat(metrics_server): drop the `userId`
  src/metrics_server/README.md
  src/metrics_server/connection_metrics.spec.ts
  src/metrics_server/connection_metrics.ts
  src/metrics_server/model.ts
  src/metrics_server/test_integration.action.sh
Labels: size/S

#1533 chore(devtools): remove reference to old directories
  .github/workflows/pull_request_checks.yml
Labels: size/XS

#1534 chore(devtools): update @typescript-eslint/eslint-plugin dependency
  package-lock.json
  package.json
Labels: size/XS

#1536 fix(server): handle `PasswordConflict` explicitly to avoid a 500
  src/shadowbox/server/manager_service.spec.ts
  src/shadowbox/server/manager_service.ts
Labels: size/XS

#1535 build: use Task
  .github/workflows/build_and_test_debug.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  Taskfile.yml
  go.mod
  go.sum
  package.json
  scripts/run_action.sh
  src/metrics_server/README.md
  src/metrics_server/Taskfile.yml
  src/metrics_server/build.action.sh
  src/metrics_server/deploy_dev.action.sh
  src/metrics_server/deploy_prod.action.sh
  src/metrics_server/start.action.sh
  src/metrics_server/test.action.sh
  src/metrics_server/test_integration.sh
  src/sentry_webhook/README.md
  src/sentry_webhook/Taskfile.yml
  src/sentry_webhook/build.action.sh
  src/sentry_webhook/deploy.action.sh
  src/sentry_webhook/test.action.sh
  src/sentry_webhook/tsconfig.json
  src/shadowbox/README.md
  src/shadowbox/Taskfile.yml
  src/shadowbox/docker/Dockerfile
  src/shadowbox/docker/build.action.sh
  src/shadowbox/docker/start.action.sh
  src/shadowbox/integration_test/README.md
  src/shadowbox/integration_test/run.action.sh
  src/shadowbox/integration_test/test.sh
  src/shadowbox/integration_test/util/Dockerfile
  src/shadowbox/server/build.action.sh
  src/shadowbox/server/start.action.sh
  src/shadowbox/test.action.sh
  third_party/outline-ss-server/.gitignore
  third_party/outline-ss-server/LICENSE
  third_party/outline-ss-server/METADATA
  third_party/outline-ss-server/Makefile
  third_party/prometheus/Makefile
  tools.go
Labels: size/XXL

#1539 fix(server): make integration test work on macOS
  package-lock.json
  src/shadowbox/Taskfile.yml
  src/shadowbox/integration_test/test.sh
Labels: size/XS

#1540 build(server): convert Makefile to Taskfile
  .gitignore
  Taskfile.yml
  src/shadowbox/Taskfile.yml
  third_party/Taskfile.yml
  third_party/prometheus/Makefile
Labels: size/XS

#1532 feat(metrics_server): do not invalidate legacy report types
  src/metrics_server/connection_metrics.spec.ts
  src/metrics_server/connection_metrics.ts
  src/metrics_server/model.ts
Labels: size/M

#1542 feat(metrics_server): add support for ASN
  package-lock.json
  src/metrics_server/README.md
  src/metrics_server/connection_metrics.spec.ts
  src/metrics_server/connection_metrics.ts
  src/metrics_server/model.ts
  src/metrics_server/test_integration.sh
Labels: size/XS
