Repository Jigsaw-Code/outline-server, pull requests merged in 2024-02, with the labels that each got.

#1494 feat(server): enable log rotation and start script
  src/server_manager/install_scripts/do_install_server.sh
  src/server_manager/install_scripts/install_server.sh
Labels: size/S

#1497 chore(manager): cleanup and fix Manager build
  src/server_manager/electron_app/build.action.sh
  src/server_manager/electron_app/package.action.sh
  src/server_manager/electron_app/start.action.sh
  src/server_manager/scripts/fill_packaging_opts.sh
  src/server_manager/scripts/finish_info_files.sh
  src/server_manager/scripts/get_electron_build_flags.mjs
  src/server_manager/scripts/get_manager_release_channel.sh
  src/server_manager/scripts/get_version.mjs
  src/server_manager/web_app/build.action.sh
Labels: size/L

#1498 chore(manager): deprecate SB_DEFAULT_SERVER_NAME on install
  src/server_manager/install_scripts/install_server.sh
Labels: size/XS

#1505 feat(server): extend key creation API to allow specifying a port
  src/shadowbox/model/access_key.ts
  src/shadowbox/model/errors.ts
  src/shadowbox/server/api.yml
  src/shadowbox/server/manager_service.spec.ts
  src/shadowbox/server/manager_service.ts
  src/shadowbox/server/server_access_key.spec.ts
  src/shadowbox/server/server_access_key.ts
Labels: size/M

#1504 test(server): add new `PUT` API to the integration test
  src/shadowbox/README.md
  src/shadowbox/integration_test/test.sh
Labels: size/XS

#1510 feat(sentry_webhook): update Salesforce record IDs for new contact form
  src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts
  src/sentry_webhook/post_sentry_event_to_salesforce.ts
Labels: size/S

#1513 chore(sentry_webhook): update UAT record ID
  src/sentry_webhook/post_sentry_event_to_salesforce.spec.ts
  src/sentry_webhook/post_sentry_event_to_salesforce.ts
Labels: size/XS
